version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
    command: streamlit run --server.port 8501 streamlit.py
    depends_on:
      - fastapi

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    command: uvicorn app:app --host 0.0.0.0 --port 8000
